denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 3.0
negative_prompt: 'blurry, low quality, worst quality, ugly, deformed, watermark, text, static'
num_frame_per_block: 3

wan_model_folder: "./checkpoints/Wan2.1-T2V-1.3B"

generator:
  model_name: Wan2.1-I2V-14B-480P
  weight_list:
    - path: "./checkpoints/Wan2.1-I2V-14B-480P"
      switch_name: true
  filter_list:
    - "img_emb."
    - "cross_attn.k_img"
    - "cross_attn.v_img"
    - "cross_attn.norm_k_img"

dataset:
  video_size:
  - 480
  - 832
  max_num_frames: 99999
  min_num_frames: 99999
  clip_root: /
  annot_root: /
  json_path: null
  target_fps: 15
  force_fps: false
  skip_frms_num: 0
  drop_last_frms_num: 0
  cond_frms_mode: null
  random_start: true
  max_clips: null
  duplicate_meta: 1
  use_loss_mask: false
  video_crop_max: -1
  cond_frms_crop_max: -1
  ref_frms_crop_max: -1
  force_to_image_prob: -1
  frame_tick_size: 8
  width_tick_size: 16
  height_tick_size: 16
  traj_txt_path: ./traj/x_y_circle_cycle.txt  # Will be overridden by run_test_pipeline.sh
  relative_to_source: false
  rotation_only: false
